In [12]:
import numpy as np

# Define matrix A (example 4x4 matrix)
A = np.array([[4, 1, 0, 0],
              [1, 3, 1, 0],
              [0, 1, 2, 1],
              [0, 0, 1, 2]])

# Define an initial vector v1 (normalize it)
v1 = np.array([1, 1, 1, 1])
v1 = v1 / np.linalg.norm(v1)  # Normalize the initial vector

In [13]:
m = 3
n = A.shape[0]

V = np.zeros((n, m + 1))  # Orthonormal basis vectors
H = np.zeros((m + 1, m))  # Hessenberg matrix
V[:, 0] = v1  # Set the first column of V as the normalized initial vector


In [14]:
for j in range(m):
    # Step 1: Matrix-vector multiplication
    w = A @ V[:, j]  # Multiply the last vector in V by A

    # Step 2: Orthonormalize w with respect to previous vectors
    for i in range(j + 1):
        H[i, j] = np.dot(V[:, i], w)  # Compute the i-th component in the j-th column of H
        w = w - H[i, j] * V[:, i]     # Subtract the component from w

    # Step 3: Compute the norm of w
    H[j + 1, j] = np.linalg.norm(w)   # Off-diagonal element of H

    # Step 4: Normalize w to get the next basis vector v_{j+1}
    if H[j + 1, j] != 0:
        V[:, j + 1] = w / H[j + 1, j]  # Add new basis vector

In [15]:
import numpy as np

def arnoldi_iteration(A, v1, m):
    """
    Perform m steps of the Arnoldi iteration on matrix A with initial vector v1.
    Returns the orthonormal basis V and the Hessenberg matrix H.
    """
    n = A.shape[0]
    V = np.zeros((n, m + 1))  # Matrix to hold orthonormal basis vectors
    H = np.zeros((m + 1, m))  # Upper Hessenberg matrix

    # Normalize the initial vector v1
    V[:, 0] = v1 / np.linalg.norm(v1)

    # Arnoldi iteration loop
    for j in range(m):
        w = A @ V[:, j]
        
        # Gram-Schmidt process
        for i in range(j + 1):
            H[i, j] = np.dot(V[:, i], w)
            w = w - H[i, j] * V[:, i]

        # Compute the next Hessenberg entry
        H[j + 1, j] = np.linalg.norm(w)
        
        # If w is non-zero, normalize and add as the next basis vector
        if H[j + 1, j] != 0:
            V[:, j + 1] = w / H[j + 1, j]

    return V[:, :m], H[:m + 1, :m]

# Example usage
A = np.array([[4, 1, 0, 0],
              [1, 3, 1, 0],
              [0, 1, 2, 1],
              [0, 0, 1, 2]])

v1 = np.array([1, 1, 1, 1])  # Initial vector
m = 3  # Number of Arnoldi steps

V, H = arnoldi_iteration(A, v1, m)
print("Orthonormal Basis V:\n", V)
print("\nHessenberg Matrix H:\n", H)

Orthonormal Basis V:
 [[ 0.5         0.45226702  0.56853524]
 [ 0.5         0.45226702 -0.21320072]
 [ 0.5        -0.15075567 -0.71066905]
 [ 0.5        -0.75377836  0.35533453]]

Hessenberg Matrix H:
 [[ 4.25000000e+00  8.29156198e-01 -4.44089210e-16]
 [ 8.29156198e-01  3.11363636e+00  7.71389216e-01]
 [ 0.00000000e+00  7.71389216e-01  2.24747475e+00]
 [ 0.00000000e+00  0.00000000e+00  9.21284664e-01]]


In [ ]:
def arnoldi(iterations, sparse_matrix, start_vector):
    H = np.zeros(shape=(iterations + 1, iterations))
    orthonormal_basis = [start_vector]
    for k in range(0, n-1):
        v = A @ orthonormal_basis[k]
        for j in range(0, k):
            H[j][k] = np.dot(orthonormal_basis[k], v)
            v = v - H[j][k] @ orthonormal_basis[j]
        H[k+1][k] = np.linalg.norm(v)
        new_orthonormal_basis_vector = v / H[k+1][k]
        orthonormal_basis.append(new_orthonormal_basis_vector)
    
    return H, orthonormal_basis


In [16]:
n = 3
H = np.zeros(shape=(n, n))
A = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])
b = np.array([1, 0, 0])

In [17]:
import numpy as np

def arnoldi(iterations, sparse_matrix, start_vector):
    n = iterations  # Number of iterations/Krylov subspace dimension
    H = np.zeros((n + 1, n))  # Hessenberg matrix, (n+1) x n
    orthonormal_basis = [start_vector / np.linalg.norm(start_vector)]  # Normalize start vector

    for k in range(n):
        v = sparse_matrix @ orthonormal_basis[k]  # Apply matrix to the k-th basis vector
        for j in range(k + 1):
            H[j, k] = np.dot(orthonormal_basis[j], v)
            v = v - H[j, k] * orthonormal_basis[j]  # Orthogonalize against existing basis

        H[k + 1, k] = np.linalg.norm(v)
        if H[k + 1, k] > 1e-10:  # Tolerance to handle near-zero norm
            orthonormal_basis.append(v / H[k + 1, k])
        else:
            break

    return H[:k + 2, :k + 1], orthonormal_basis

In [20]:
A = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])
b = np.array([1, 0, 0])

H, basis_vectors = arnoldi(3, A, b)

print(H)
print(basis_vectors)

Q_two = np.array([[1, 0],[0, -1], [0, 0]])
Q_three = np.array([[1, 0, 0], [0, -1, 0], [0, 0, 1]])

print(Q_three @ A @ Q_two)

[[2. 1. 0.]
 [1. 2. 1.]
 [0. 1. 2.]
 [0. 0. 0.]]
[array([1., 0., 0.]), array([ 0., -1.,  0.]), array([0., 0., 1.])]
[[2 1]
 [1 2]
 [0 1]]


In [23]:
# Because some computer scientist a long time ago decided to start series for n=0 we have Q_three is Q_two in the textbook
tridiagonal = np.transpose(Q_three) @ A @ Q_three
print(tridiagonal)

[[2 1 0]
 [1 2 1]
 [0 1 2]]


In [30]:
from sympy import Matrix, symbols, diff, solve, Eq

# Define symbolic variables for x
C, D = symbols('C D')
x = Matrix([C, D])

# Define matrices A and b
A = Matrix([[1, 0], [1, 1], [1, 3], [1, 4]])
b = Matrix([0, 8, 9, 20])

# Compute ||Ax - b||^2
Ax_minus_b = A * x - b
norm_squared = (Ax_minus_b.T * Ax_minus_b)[0]

E = norm_squared.simplify()

partial_C = E.diff(C)
partial_D = E.diff(D)


# Define equations
equation1 = Eq(partial_C, 0)
equation2 = Eq(partial_D, 0)

# Solve the system
solution = solve((equation1, equation2), (C, D))

# Display the solution
solution

{C: 21/20, D: 41/10}

In [32]:
xval = 21/20
yval = 41/10

vector = np.array([xval, yval]) / 2

[0.525 2.05 ]
